name: NPM build index.html

on:
  push:
    branches:
      - master
      - draft

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Use Node.js
      uses: actions/setup-node@master
      with:
        node-version: '12'
    - name: Install TiddlyDnD
      run: npm install git+https://github.com/WkoD/TiddlyDnD.git
    - name: Build TiddlyWiki index.html
      run: $(npm bin)/tiddlywiki --output ./twpage --build index
    - if: ${{ steps.extract_branch.outputs.branch }} != 'master'
      name: Rename ${{ steps.extract_branch.outputs.branch }} index.html
      run: mv ./twpage/index.html ./twpage/${{ steps.extract_branch.outputs.branch }}.html
    - name: Deploy to gh_pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./twpage
        keep_files: true