name: NPM Index.html build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: npm install git+https://github.com/WkoD/TiddlyDnD.git
    - run: $(npm bin)/tiddlywiki --output . --build index
    - name: push index
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add index.html
        git commit -m "Index aktualisiert"
        git push