name: NPM Index.html build draft

on:
  push:
    branches:
      - draft

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: npm install git+https://github.com/WkoD/TiddlyDnD.git
    - run: $(npm bin)/tiddlywiki --output ./twpage --build index
    - run: |
        mv ./twpage/index.html ./twpage/draft.html
    - name: Deploy Index
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./twpage
        keep_files: true