name: NPM build index.html

on:
  push:
    branches:
      - master
      - draft

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Use Node.js
      uses: actions/setup-node@master
      with:
        node-version: '12'
    - name: Install TiddlyDnD
      run: npm install git+https://github.com/WkoD/TiddlyDnD.git
    - if: github.ref != 'refs/heads/master'
      name: Update SiteTitle.tid for branches other than master
      run: echo " ${{ steps.extract_branch.outputs.branch }}" >> ./tiddlers/$__SiteTitle.tid
    - name: Build TiddlyWiki index.html
      run: $(npm bin)/tiddlywiki --output . --build index
    - if: github.ref != 'refs/heads/master'
      name: Rename index.html for branches other than master
      run: mv ./index.html ./${{ steps.extract_branch.outputs.branch }}.html
    - name: Deploy to gh_pages
      uses: peaceiris/actions-gh-pages@v3.6.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: '.github,node_modules,tiddlers,package-lock.json,tiddlywiki.info'