name: DnDWiki merge

on:
  workflow_dispatch:

jobs:
  repo-merge:
    if: ${{ github.repository }} != 'WkoD/DnDWiki'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-merge master
      uses: WkoD/git-merge@master
      with:
        source_repo: "https://github.com/WkoD/DnDWiki.git"
        source_branch: "master"
        destination_repo: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        destination_branch: "master"
    - name: repo-merge draft
      uses: WkoD/git-merge@master
      with:
        source_repo: "https://github.com/WkoD/DnDWiki.git"
        source_branch: "draft"
        destination_repo: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        destination_branch: "draft"
    - name: Dispatch to master
      run: |
        curl -X POST \
        "https://api.github.com/repos/${{ github.repository }}/actions/workflows/npm-build-pages.yml/dispatches" \
        -H 'Accept: application/vnd.github.v3+json' \
        -u ${{ secrets.DISPATCH_PAT }} \
        -d '{"ref":"master"}'
