name: DnDWiki merge

on:
  workflow_dispatch:

jobs:
  repo-merge:
    if: ${{ github.repository }} != 'WkoD/DnDWiki'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
    - name: merge master
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git pull 'https://github.com/WkoD/DnDWiki.git' master
        git push origin master
    - name: merge draft
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email
        git checkout draft
        git pull 'https://github.com/WkoD/DnDWiki.git' draft
        git push origin draft
